---
title: Gignar.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
url: http://oliverjam.es
theme:
  title: Oliver James
  avatar: avatar.png
  gravatar: 
  description: A website with blog posts and pages.
  header_text: |
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  footer_text: |
    Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type.html">Type</a>
  rss: false
  email_address: 
  behance: 
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: gignar
  google_plus: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  tumblr: 
  twitter: 
  wordpress: 
  youtube: 
  google_analytics: 
  disqus_shortname: 
  str_follow_on: Follow on
  str_rss_follow: Follow RSS feed
  str_email: Email
  str_next: Next
  str_prev: Prev
  str_continue_reading: Continue reading
paginate: 5
paginate_path: blog/page:num
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
